apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "testing.fullname" . }}
data:
  planName: {{ .Values.planName | quote }}
  {{- if .Values.additionalData }}
  additionalData: {{ .Values.additionalData | quote }}
  {{- end }}