apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: redis-conflict
spec:
  externalID: set-here-existing-instance-external-id
  clusterServiceClassExternalName: redis
  clusterServicePlanExternalName: micro
  # parameters must differ from the already provisioned instance
  parameters:
    imagePullPolicy: Always
