/*
Copyright 2020 The Helm Broker Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kyma-project/helm-broker/pkg/apis/addons/v1alpha1"
	scheme "github.com/kyma-project/helm-broker/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AddonsConfigurationsGetter has a method to return a AddonsConfigurationInterface.
// A group's client should implement this interface.
type AddonsConfigurationsGetter interface {
	AddonsConfigurations(namespace string) AddonsConfigurationInterface
}

// AddonsConfigurationInterface has methods to work with AddonsConfiguration resources.
type AddonsConfigurationInterface interface {
	Create(ctx context.Context, addonsConfiguration *v1alpha1.AddonsConfiguration, opts v1.CreateOptions) (*v1alpha1.AddonsConfiguration, error)
	Update(ctx context.Context, addonsConfiguration *v1alpha1.AddonsConfiguration, opts v1.UpdateOptions) (*v1alpha1.AddonsConfiguration, error)
	UpdateStatus(ctx context.Context, addonsConfiguration *v1alpha1.AddonsConfiguration, opts v1.UpdateOptions) (*v1alpha1.AddonsConfiguration, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.AddonsConfiguration, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.AddonsConfigurationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AddonsConfiguration, err error)
	AddonsConfigurationExpansion
}

// addonsConfigurations implements AddonsConfigurationInterface
type addonsConfigurations struct {
	client rest.Interface
	ns     string
}

// newAddonsConfigurations returns a AddonsConfigurations
func newAddonsConfigurations(c *AddonsV1alpha1Client, namespace string) *addonsConfigurations {
	return &addonsConfigurations{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the addonsConfiguration, and returns the corresponding addonsConfiguration object, and an error if there is any.
func (c *addonsConfigurations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AddonsConfiguration, err error) {
	result = &v1alpha1.AddonsConfiguration{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("addonsconfigurations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AddonsConfigurations that match those selectors.
func (c *addonsConfigurations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AddonsConfigurationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AddonsConfigurationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("addonsconfigurations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested addonsConfigurations.
func (c *addonsConfigurations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("addonsconfigurations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a addonsConfiguration and creates it.  Returns the server's representation of the addonsConfiguration, and an error, if there is any.
func (c *addonsConfigurations) Create(ctx context.Context, addonsConfiguration *v1alpha1.AddonsConfiguration, opts v1.CreateOptions) (result *v1alpha1.AddonsConfiguration, err error) {
	result = &v1alpha1.AddonsConfiguration{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("addonsconfigurations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(addonsConfiguration).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a addonsConfiguration and updates it. Returns the server's representation of the addonsConfiguration, and an error, if there is any.
func (c *addonsConfigurations) Update(ctx context.Context, addonsConfiguration *v1alpha1.AddonsConfiguration, opts v1.UpdateOptions) (result *v1alpha1.AddonsConfiguration, err error) {
	result = &v1alpha1.AddonsConfiguration{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("addonsconfigurations").
		Name(addonsConfiguration.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(addonsConfiguration).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *addonsConfigurations) UpdateStatus(ctx context.Context, addonsConfiguration *v1alpha1.AddonsConfiguration, opts v1.UpdateOptions) (result *v1alpha1.AddonsConfiguration, err error) {
	result = &v1alpha1.AddonsConfiguration{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("addonsconfigurations").
		Name(addonsConfiguration.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(addonsConfiguration).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the addonsConfiguration and deletes it. Returns an error if one occurs.
func (c *addonsConfigurations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("addonsconfigurations").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *addonsConfigurations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("addonsconfigurations").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched addonsConfiguration.
func (c *addonsConfigurations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AddonsConfiguration, err error) {
	result = &v1alpha1.AddonsConfiguration{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("addonsconfigurations").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
