// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import internal "github.com/kyma-project/helm-broker/internal"
import mock "github.com/stretchr/testify/mock"

// instanceBindDataInserter is an autogenerated mock type for the instanceBindDataInserter type
type instanceBindDataInserter struct {
	mock.Mock
}

// Insert provides a mock function with given fields: _a0
func (_m *instanceBindDataInserter) Insert(_a0 *internal.InstanceBindData) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*internal.InstanceBindData) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
