global:
  containerRegistry:
    path: ""
  helm_broker:
    dir: ""
    version: "latest"
  helm_controller:
    dir: ""
    version: "latest"

tests:
  image: helm-broker-tests
  dir: ""
  tag: "latest"

webhook:
  image: "helm-broker-webhook:latest"
  imagePullPolicy: IfNotPresent
  securityContext: {runAsUser: 1001}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  minReadySeconds: 1
  annotations:
    sidecar.istio.io/inject: "false"
  healthcheck:
    enabled: false
  # Attributes of the webhook's service resource
  service:
    port: 8443
    targetPort: 8443
  # Webhook resource requests and limits
  # Ref: http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      cpu: 100m
      memory: 20Mi
    limits:
      cpu: 100m
      memory: 30Mi
