// Code generated by mockery v1.0.0
package automock

import mock "github.com/stretchr/testify/mock"
import v1alpha1 "github.com/kyma-project/helm-broker/pkg/apis/addons/v1alpha1"

// TemplateService is an autogenerated mock type for the TemplateService type
type TemplateService struct {
	mock.Mock
}

// SetNamespace provides a mock function with given fields: namespace
func (_m *TemplateService) SetNamespace(namespace string) {
	_m.Called(namespace)
}

// TemplateURL provides a mock function with given fields: repository
func (_m *TemplateService) TemplateURL(repository v1alpha1.SpecRepository) (string, error) {
	ret := _m.Called(repository)

	var r0 string
	if rf, ok := ret.Get(0).(func(v1alpha1.SpecRepository) string); ok {
		r0 = rf(repository)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(v1alpha1.SpecRepository) error); ok {
		r1 = rf(repository)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
