apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      serviceAccountName: {{ template "fullname" . }}

      initContainers:
      - name: "init-{{ .Chart.Name }}"
        image: "eu.gcr.io/kyma-project/health-check-proxy:PR-6466"
        imagePullPolicy: {{ .Values.global.initImage.pullPolicy }}
        command:
          - "/health-check"
          - "-path=health"
          - "-host={{ .Release.Name }}-etcd-stateful-client.{{ .Release.Namespace }}.svc.cluster.local"
          - "-statusPort={{ .Values.global.etcdClientPort }}"
          - "-retry=20"
        ports:
          - containerPort: {{ .Values.broker.internalPort }}

      containers:
      - name: broker
        image: "{{ .Values.global.containerRegistry.path }}{{ .Values.global.helm_broker.dir }}/{{ .Values.global.helm_broker.image }}:{{ .Values.global.helm_broker.version }}"
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        env:
          - name: APP_TMP_DIR
            value: /tmp
          - name: APP_PORT
            value: "{{ .Values.broker.internalPort }}"
          - name: APP_STATUS_PORT
            value: "{{ .Values.broker.statusPort }}"
          - name: APP_CONFIG_FILE_NAME
            value: /etc/config/helm-broker/config.yaml
          - name: APP_HELM_TILLER_HOST
            value: "tiller-deploy.kube-system.svc.cluster.local:44134"
          - name: APP_HELM_TILLER_TLS_INSECURE
            value: "{{ .Values.broker.tillerTLSInsecure }}"
          - name: APP_HELM_TILLER_TLS_ENABLED
            value: "{{ .Values.broker.tillerTLSEnabled }}"
        volumeMounts:
        - mountPath: /tmp
          name: tmp-empty-dir
        - mountPath: /etc/config/helm-broker
          name: config-volume
        - mountPath: /etc/certs
          name: helm-certs
          readOnly: true
        ports:
        - containerPort: {{ .Values.broker.internalPort }}
        # We use health-check binary to monitor the state of application
        # Current solution is suited for deployment on cluster with mTLS enabled
        # https://medium.com/cloud-native-the-gathering/kubernetes-liveness-probe-for-scratch-image-with-istio-mtls-enabled-90543e4bae34
        readinessProbe:
          exec:
            command:
              - "/health-check"
              - "-path=ready"
              - "-statusPort={{ .Values.broker.statusPort }}"
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          exec:
            command:
              - "/health-check"
              - "-path=live"
              - "-statusPort={{ .Values.broker.statusPort }}"
          periodSeconds: 10
          timeoutSeconds: 2
          successThreshold: 1

      - name: ctrl
        image: "{{ .Values.global.containerRegistry.path }}{{ .Values.global.helm_controller.dir }}/{{ .Values.global.helm_controller.image }}:{{ .Values.global.helm_controller.version }}"
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        env:
          - name: APP_TMP_DIR
            value: /tmp
          - name: APP_STATUS_PORT
            value: "{{ .Values.ctrl.statusPort }}"
          - name: APP_NAMESPACE
            value: {{ .Release.Namespace }}
          - name: APP_SERVICE_NAME
            value: {{ template "fullname" . }}
          - name: APP_CONFIG_FILE_NAME
            value: /etc/config/helm-broker/config.yaml
          - name: APP_CLUSTER_SERVICE_BROKER_NAME
            value: {{ template "fullname" . }}
          - name: APP_DEVELOP_MODE
            value: "{{ .Values.global.isDevelopMode }}"
          - name: APP_DOCUMENTATION_ENABLED
            value: "{{ .Values.ctrl.documentationEnabled }}"
        volumeMounts:
        - mountPath: /tmp
          name: tmp-empty-dir
        - mountPath: /etc/config/helm-broker
          name: config-volume
        - mountPath: /etc/certs
          name: helm-certs
          readOnly: true
        - mountPath: /root/.ssh
          name: ssh-cfg
          readOnly: true
        ports:
        - containerPort: {{ .Values.ctrl.internalPort }}
        readinessProbe:
          exec:
            command:
              - "/health-check"
              - "-path=ready"
              - "-statusPort={{ .Values.ctrl.statusPort }}"
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          exec:
            command:
              - "/health-check"
              - "-path=live"
              - "-statusPort={{ .Values.ctrl.statusPort }}"
          periodSeconds: 60
          timeoutSeconds: 30
          successThreshold: 1

      volumes:
      - name: tmp-empty-dir
        emptyDir:
          sizeLimit: "{{ .Values.global.tmpDirSizeLimit }}"
      - name: config-volume
        configMap:
          name: helm-config-map
      - name: ssh-cfg
        configMap:
          name: ssh-cfg
      - name: helm-certs
        secret:
          secretName: helm-secret
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
