{{- $ca := genCA "helm-broker" 3650 }}
{{- $cn := printf "%s-helm-broker" (include "fullname" .) }}
{{- $altName1 := printf "%s.%s" $cn .Release.Namespace }}
{{- $altName2 := printf "%s.%s.svc" $cn .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $altName1 $altName2) 3650 $ca }}
apiVersion: v1
data:
    tls.crt: {{ b64enc $cert.Cert }}
    tls.key: {{ b64enc $cert.Key }}
kind: Secret
metadata:
  name: helm-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
