kind: Service
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.global.service.type }}
  selector:
    app: {{ template "fullname" . }}
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    name: http-hb-port
    port: {{ .Values.global.service.externalPort }}
    targetPort: {{ .Values.global.service.internalPort }}
