/*
Copyright 2020 The Helm Broker Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kyma-project/helm-broker/pkg/apis/addons/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterAddonsConfigurations implements ClusterAddonsConfigurationInterface
type FakeClusterAddonsConfigurations struct {
	Fake *FakeAddonsV1alpha1
}

var clusteraddonsconfigurationsResource = schema.GroupVersionResource{Group: "addons.kyma-project.io", Version: "v1alpha1", Resource: "clusteraddonsconfigurations"}

var clusteraddonsconfigurationsKind = schema.GroupVersionKind{Group: "addons.kyma-project.io", Version: "v1alpha1", Kind: "ClusterAddonsConfiguration"}

// Get takes name of the clusterAddonsConfiguration, and returns the corresponding clusterAddonsConfiguration object, and an error if there is any.
func (c *FakeClusterAddonsConfigurations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterAddonsConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clusteraddonsconfigurationsResource, name), &v1alpha1.ClusterAddonsConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterAddonsConfiguration), err
}

// List takes label and field selectors, and returns the list of ClusterAddonsConfigurations that match those selectors.
func (c *FakeClusterAddonsConfigurations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterAddonsConfigurationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clusteraddonsconfigurationsResource, clusteraddonsconfigurationsKind, opts), &v1alpha1.ClusterAddonsConfigurationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterAddonsConfigurationList{ListMeta: obj.(*v1alpha1.ClusterAddonsConfigurationList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterAddonsConfigurationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterAddonsConfigurations.
func (c *FakeClusterAddonsConfigurations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clusteraddonsconfigurationsResource, opts))
}

// Create takes the representation of a clusterAddonsConfiguration and creates it.  Returns the server's representation of the clusterAddonsConfiguration, and an error, if there is any.
func (c *FakeClusterAddonsConfigurations) Create(ctx context.Context, clusterAddonsConfiguration *v1alpha1.ClusterAddonsConfiguration, opts v1.CreateOptions) (result *v1alpha1.ClusterAddonsConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clusteraddonsconfigurationsResource, clusterAddonsConfiguration), &v1alpha1.ClusterAddonsConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterAddonsConfiguration), err
}

// Update takes the representation of a clusterAddonsConfiguration and updates it. Returns the server's representation of the clusterAddonsConfiguration, and an error, if there is any.
func (c *FakeClusterAddonsConfigurations) Update(ctx context.Context, clusterAddonsConfiguration *v1alpha1.ClusterAddonsConfiguration, opts v1.UpdateOptions) (result *v1alpha1.ClusterAddonsConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clusteraddonsconfigurationsResource, clusterAddonsConfiguration), &v1alpha1.ClusterAddonsConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterAddonsConfiguration), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterAddonsConfigurations) UpdateStatus(ctx context.Context, clusterAddonsConfiguration *v1alpha1.ClusterAddonsConfiguration, opts v1.UpdateOptions) (*v1alpha1.ClusterAddonsConfiguration, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clusteraddonsconfigurationsResource, "status", clusterAddonsConfiguration), &v1alpha1.ClusterAddonsConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterAddonsConfiguration), err
}

// Delete takes name of the clusterAddonsConfiguration and deletes it. Returns an error if one occurs.
func (c *FakeClusterAddonsConfigurations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(clusteraddonsconfigurationsResource, name), &v1alpha1.ClusterAddonsConfiguration{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterAddonsConfigurations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clusteraddonsconfigurationsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterAddonsConfigurationList{})
	return err
}

// Patch applies the patch and returns the patched clusterAddonsConfiguration.
func (c *FakeClusterAddonsConfigurations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterAddonsConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clusteraddonsconfigurationsResource, name, pt, data, subresources...), &v1alpha1.ClusterAddonsConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterAddonsConfiguration), err
}
