// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import mock "github.com/stretchr/testify/mock"
import rafter "github.com/kyma-project/helm-broker/internal/rafter"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Upload provides a mock function with given fields: fileName, contents
func (_m *Client) Upload(fileName string, contents []byte) (rafter.UploadedFile, error) {
	ret := _m.Called(fileName, contents)

	var r0 rafter.UploadedFile
	if rf, ok := ret.Get(0).(func(string, []byte) rafter.UploadedFile); ok {
		r0 = rf(fileName, contents)
	} else {
		r0 = ret.Get(0).(rafter.UploadedFile)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, []byte) error); ok {
		r1 = rf(fileName, contents)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
